### ISSUE TITLE
GetBusiness does not handle unicode business ids

### ISSUE THREAD

**Issue by egrubbs** [mathisonian/python-yelp-v2#14]
The Search function returned this business id:
```
u'red-cat-jazz-caf\xe9-houston-3'
```
GetCachedTime() cannot handle unicode objects, and urllib requires non-ascii characters in a utf-8 string to be escaped. Therefore, to get GetBusiness() to work, I had to call it like this:
```
business = yelp_api.GetBusiness(urllib.quote(business.id.encode('utf-8')))
```
I have to use GetBusiness() since Search() does not include the review.

**Comment by mathisonian** [comment]
Ah, good catch @egrubbs! 

Would you be willing to take a stab at a patch for this, and I'll update on pypi?
